import { precacheAndRoute } from 'workbox-precaching';

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest below.
precacheAndRoute(self.__WB_MANIFEST);
